<footer>
    <div class="ui  segment">
        <div class="ui main text container">
            <div class="ui stackable inverted divided equal height stackable grid">               
                <div class="seven wide column">
                    <p> <?= round((microtime(1) - START_TIME) * 1000, 4), ' ms. | ', number_format(memory_get_usage() / 1048576, 2), ' MB'; ?></p>
                </div>
            </div>
        </div>
    </div>


</footer>
