
<div class="ui secondary pointing menu">
    <a class="active item">
        Inicio
    </a>
    <a class="item" href="<?php echo URL_DOMAIN ?>dominios/index">
        Dominos
    </a>
    <a class="item" href="<?php echo URL_DOMAIN ?>proveedores/index">
        Proveedores
    </a>
    <a class="item">
        opciones
    </a>
    <div class="right menu">
        <a class="ui item">
            salir
        </a>
    </div>
</div>