<footer>
    <div class="ui inverted vertical footer segment">
        <div class="ui main text container">
            <div class="ui stackable inverted divided equal height stackable grid">
                <div class="three wide column">
                    <h4 class="ui inverted header">About</h4>
                    <div class="ui inverted link list">
                        <a href="#" class="item">Sitemap</a>
                    </div>
                </div>
                <div class="three wide column">
                    <h4 class="ui inverted header">Services</h4>
                    <div class="ui inverted link list">
                        <a href="#" class="item">Banana Pre-Order</a>
                    </div>
                </div>
                <div class="seven wide column">
                    <h4 class="ui inverted header">Footer Header</h4>
                    <p><?= round((microtime(1) - START_TIME) * 1000, 4), ' ms. |', number_format(memory_get_usage() / 1048576, 2), ' MB'; ?></p>
                </div>
            </div>
        </div>
    </div>

    
</footer>
