<h3 class="ui header dividing">Happy Domain, KumbiaPHP</h3>
<p>Esto sera una aplicación para llevar el control de nuestros dominios!</p>

<div class="ui bulleted list">
    <div class="item">
         <div>Modulos</div>
        <div class="list">
            <div class="item">Dominios</div>
            <div class="item">Fechas de vencimiento</div>
            <div class="item">Proveedores</div>
            <div class="item">Servidores DNS</div>
            <div class="item">Informacion adicional</div>
        </div>
    </div>
</div>
