<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset=<?= APP_CHARSET ?> >
        <title>HappyDomain</title>
        <?php Tag::css('semantic.min') ?>
        <?= Html::includeCss() ?>
    </head>
    <body>
        <div class="ui main text container">
            <div class="ui container">
                <header class="row">
                    <h1 class="ui header dividing">HappyDomain</h1>
                    <?php View::partial('menu') ?>
                </header>

                <div class="ui segment">
                    <?php View::content() ?>
                </div>

                <?php View::partial('footer') ?>
                
                <?php View::partial('analytics') ?>
            </div>
        </div>
    </body>
</html>
